config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  resources :pages
  resources :locations
  post 'locations/new_review' => 'locations#new_review', as: :new_review
  resources :users, except: [:destroy]
  get 'users/new' => 'users#new', :as => :new
  resource :sessions, only: [:create, :new, :destroy]

end

app/models/location.rb
class Location
  include Mongoid::Document
  include Geocoder::Model::Mongoid
  field :name, type: String
  field :address, type: String
  field :description, type: String
  field :coordinates, :type => Array
  field :nearby, type: String
  field :resources, type: String
  field :wifi, type: String
  field :noise, type: String

  has_many :reviews
  validates_presence_of :address

  geocoded_by :address           
  reverse_geocoded_by :coordinates
  after_validation :geocode, :if => :address_changed?

end

app/models/review.rb
class Review
  include Mongoid::Document
  field :title, type: String
  field :body, type: String

  belongs_to :location
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  has_secure_password
  field :name, type: String
  field :email, type: String
  field :password_digest, type: String

  validates_uniqueness_of :email
  validates_presence_of :email, :password_digest
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :authorize
  protect_from_forgery with: :exception
  helper_method :current_user 
  
  def current_user   
      @current_user ||= User.where(id: session[:user_id]).first 
  end

  def authorize
    redirect_to new_sessions_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
    
  end

  def show
    @location = Location.find(params[:id])
    @locations = Location.all
    @review = Review.new
    @nearby = Location.near(@location, 10,  :order => "distance").to_a
  end

  def new
    @location = Location.new
  end

  def new_review
    @id = params[:location_id]
    @location = Location.find(@id)
    @location.reviews << Review.new(params.require(:review).permit(:title, :body))
    if @location.save
      redirect_to location_path(@id)
    end
  end

  def create
    @location = Location.new(params.require(:location).permit(:name, :address, :resources, :wifi, :noise, :description))
    if @location.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @location = Location.find(params[:id])

  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(params.require(:location).permit(:name, :address, :resources, :wifi, :noise, :description))
      redirect_to location_path(@location.id)
    else
      render 'edit'
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to root_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_filter :authorize

  def index
    @locations = Location.all
    @location = Location.new
    @users = User.all
    @user = User.new
  end

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :authorize

  def new
    # Present an empty login form
    @user = User.new
    @is_login = true
  end

  def create
    # Find the user that is trying to log in    
    u = User.where(email: params[:user][:email]).first
    if u && u.authenticate(params[:user][:password])
      # Store as a cookie in the users' browser the ID of them,
      # indicating that they are logged in
      session[:user_id] = u.id.to_s
      redirect_to pages_path
    else
      # Go back to the login page
      redirect_to new_sessions_path
    end
  end

  def destroy
    reset_session
    redirect_to pages_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :authorize

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>project 2.1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Office Hours</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
            <li>
              <% if current_user %>
                <%= link_to "Logout", sessions_path, method: :delete %>
              <% else %>
                
              <% end %>
            </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </nav>


<%= yield %>  



</body>
</html>

app/views/locations/_form.html.erb
<a href id="editlink" data-toggle="modal" data-target="#editModal">EDIT</a>


<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit this location</h4>
      </div>
        <div class="modal-body">

          <%= bootstrap_form_for(@location) do |f| %>
            <% if @location.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

                <ul>
                <% @location.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="field">
              <%= f.text_field :name %>
            </div>

            <div class="field">
              <%= f.text_field :address %>
            </div>

            <%if @location.coordinates %>
              <div class="field">
                <%= f.text_field :coordinates %>
              </div>
            <%end%>

            <div class="field">
              <%= f.text_field :resources %>
            </div>

            <div class="field">
              <%= f.text_field :wifi %>
            </div>

            <div class="field">
              <%= f.text_field :noise %>
            </div>

            <div class="field">
              <%= f.text_field :description %>
            </div>
            
            <div class="actions">
              <%= f.submit %>
            </div>

          <% end %>

      </div>
    </div>
  </div>
</div>

app/views/locations/edit.html.erb
<!-- <h1>Editing location</h1>
 -->
<%#= render 'form' %>

<%#= link_to 'Show', @location %> |
<%#= link_to 'Back', "javascript:history.back()" %>

app/views/locations/index.html.erb
<% @locations.each do |location| %>
  <ul>
    <%= location.name %> <%=link_to "See more", location_path(location) %>
    <li><%= location.address %></li>
    <li><%= location.description %></li>
  </ul>
<% end %>

app/views/locations/new.html.erb
<%= render 'form' %>

app/views/locations/show.html.erb
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>

<body>

  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-6">
        <div class="descBox">
          
          <h2><%= @location.name.upcase %></h2>
          <p><%= @location.address.upcase %></p>
          Resources: <%= @location.resources %><br>
          Wifi: <%= @location.wifi %><br>
          Noise Level: <%= @location.noise %><br><br>
          <%= @location.description %><br><br>
          <span id="editcontrols"><%#= link_to 'Edit'.upcase, edit_location_path %> <%= render 'locations/form' %> // <%= link_to 'Delete'.upcase, @location, method: :delete, data: { confirm: 'Are you sure you want to delete it?'} %></span><hr>
          
        </div>
        <div class="nearbyBox">
          <p>This spot too crowded? Check out some others near you.</p>
            <% if @nearby.length > 1 %>
              <ul>
                <% for index in (1...@nearby.length) %>
                  <li><%= link_to @nearby[index].name, location_path(@nearby[index]) %></li>
              <% end %>
              </ul>
            <% else %>
              <ul><li>Looks like there aren't any other spots near you! :(</li></ul> 
            <% end %>
        </div>
        <hr>
        <%= link_to 'Back', root_path %>

      </div>

      <div class="col-xs-4">
        <h2>REVIEWS</h2>
          <% if @location.reviews.count > 0 %>
              <% @location.reviews.each do |review| %>
                <p><strong><%= review.title %></strong><br>
                <%= review.body %></p>
              <% end %>
          <% else %>
            <p>No reviews yet! Be the first to write a review.</p>
          <% end %>

        <%= bootstrap_form_for(@review ,:url => {:action => :new_review, :controller => :locations} ) do |f| %>
          <%= hidden_field_tag :location_id, @location.id %>
          <div class="field">
            <%= f.text_field :title%>
          </div>
          <div class="field">
            <%= f.text_field :body%>
          </div>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/pages/_login.html.erb
<button id="buttons" type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#loginModal">Login</button>


<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Welcome Back</h4>
      </div>
        <div class="modal-body">

          <%= bootstrap_form_for(@user, {url:sessions_path}) do |f| %>
          
            <div class="field">
              
              <%= f.text_field :email %>
            </div>
            <div class="field">
              
              <%= f.password_field :password %>
            </div>
            <div class="actions">
              <%= f.submit "Submit" %>
            </div>
            <% end %>

      </div>
    </div>
  </div>
</div>

app/views/pages/_signup.html.erb
<button id="buttons" type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#signupModal">Sign Up</button>


<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Register</h4>
      </div>
        <div class="modal-body">

          <%= bootstrap_form_for(@user) do |f| %>

            <div class="field">
              <%= f.text_field :name %>
            </div>
            <div class="field">
              <%= f.text_field :email %>
            </div>
            <div class="field">
              <%= f.password_field :password %>
            </div>
            <div class="field">
              <%= f.password_field :password_confirmation %>
            </div>
            <div class="actions">
              <%= f.submit "Submit" %>
            </div>
          <% end %>


      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
  <% if current_user %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-6">
<!--           <h1>Welcome back, <%= current_user.name %></h1>
 -->          <h2>LOCATIONS</h2>

  <!--           <div class="row">
            <div class="col-xs-4">hi</div>
            <div class="col-xs-4">bye</div>
            <div class="col-xs-4">still here</div>
          </div>
  -->

          <p>
          <% @locations.each do |location| %>
            <div class="box">
              <ul class="row" id="thumbgrid">
                <li class="col-xs-10">
                  <%= location.name %><br>
                  <%=link_to "See more", location_path(location) %>
                </li>
              </ul>
  <!--                 <li><%#= location.address %></li>
              <li><%#= location.description %></li> -->
            </div>
          <% end %>
          </p>
          
        </div>
        <div class="col-xs-4">
          <h2>ADD A LOCATION</h2>

          <%= bootstrap_form_for(@location) do |f| %>
            <% if @location.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

                <ul>
                <% @location.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="field">
              <%= f.text_field :name %>
            </div>

            <div class="field">
              <%= f.text_field :address %>
            </div>

            <%if @location.coordinates %>
              <div class="field">
                <%= f.text_field :coordinates %>
              </div>
            <%end%>

            <div class="field">
              <%= f.text_field :resources %>
            </div>

            <div class="field">
              <%= f.text_field :wifi %>
            </div>

            <div class="field">
              <%= f.text_field :noise %>
            </div>

            <div class="field">
              <%= f.text_field :description %>
            </div>
            
            <div class="actions">
              <%= f.submit %>
            </div>

          <% end %>

      </div>
    </div>
  </div>
</div>

          
        </div>
      </div>
    </div>

    <% else %>

  <div class="splashpage">
      <div id="splash">

        <%= render 'login' %>

        <%= render 'signup' %>
      </div>
  </div>
  <% end %>

</div>

app/views/users/_form.html.erb
<%= bootstrap_form_for(@user) do |f| %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>Password confirmation</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.password_confirmation %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div id="signupwindow">
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', "javascript:history.back()" %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @user.password_confirmation %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>